"use client";

import ProtocolHeader from "@/components/header/header";
import BackgroundParticles from "@/components/particles/BackgroundParticles";
import ProtocolFooter from "@/components/footer/footer";

const SECTIONS = [
  {
    id: "proposition",
    heading: "0. The Proposition",
    body: `AI can generate a face. AI can clone a voice. AI can forge a fingerprint.
But AI cannot generate you — because you are not a file. You are a field.

This document explains why the most advanced AI models on Earth — including DeepSeek, GPT-5, and multimodal motion diffusion architectures — structurally fail to replicate the deep kinetic signature of a living human body. It is not a claim about temporary AI limitations. It is a claim about physics, information theory, and the irreducible entropy of biological control systems.`,
  },
  {
    id: "physics",
    heading: "1. The Physics of Unforgeability",
    body: `The human motor system is not a transformer. It is a multi-scale, non-linear, noise-driven biological control system built from motor units (asynchronous stochastic recruitment at 5–50 Hz), the stretch reflex arc (~25 ms feedback loop producing 8–12 Hz micro-oscillations), the corticospinal tract (50–80 m/s conduction, creating individual-specific timing signatures), cerebellar feedforward (always slightly wrong, producing 3–5 Hz error-correction micro-motions), and musculoskeletal biomechanics (bone lengths, joint surface geometries, tendon stiffness — physically unique to each body).

These are not "features" that can be extracted and replicated. They are physical properties of a specific human body.

AI-generated motion, trained with L2 loss, is mathematically optimized to suppress high-frequency, low-amplitude signals — exactly the signals that make human motion human. The optimal L2 predictor is the conditional mean of the training distribution. It converges to the average motion, not any specific human's motion. The result: AI motion looks correct to the human eye but is kinematically sterile — too smooth, too regular, too average.`,
  },
  {
    id: "info-theory",
    heading: "2. The Information-Theoretic Limit",
    body: `Even with infinite training data, an AI model faces a fundamental information bottleneck:

Nyquist limit: 2D video at 30 fps cannot resolve dynamics above 15 Hz. The 8–12 Hz physiological tremor band is at the Nyquist boundary — its phase information is fundamentally aliased in any video-based training set.

Depth ambiguity: 2D→3D lifting is ill-posed. True skeletal proportions in 3D are underdetermined from 2D projections alone. A femur that appears 42 cm on screen might be anywhere from 38–46 cm — a ±10% uncertainty propagating through the entire kinematic chain.

Sensor noise floor: Even high-quality 3D pose data carries measurement noise at the millimeter scale — precisely the scale of the micro-kinematic signals that distinguish individuals.

The consequence: no finite training dataset can fully determine a target's Motion Signature. There is an irreducible gap — not because AI is not good enough yet, but because the information is not in the data.`,
  },
  {
    id: "engine",
    heading: "3. The MyShape Motion Signature Engine",
    body: `The MyShape core engine is written in Rust. It compiles to native binaries (macOS, Linux, Windows) and WebAssembly. It has zero runtime dependencies beyond the Rust standard library and a handful of audited cryptographic and linear algebra crates.

The engine extracts a 128-dimensional Motion Signature vector from raw 3D pose sequences across four independent feature groups:

Φ_K — Kinematics (40 dims): Skeletal ratios between 14 bone segments, 6 joint angle variances, velocity and acceleration statistics for 5 representative keypoints.

Φ_A — Acceleration Profile (25 dims): Per-keypoint statistical distribution including Hurst exponent. Human acceleration: H ≈ 0.6–0.8 (long-range dependence). AI acceleration: H ≈ 0.5 (uncorrelated noise).

Φ_J — Jerk Profile (25 dims): The third temporal derivative of position — rate of change of acceleration. Per-keypoint statistics including median absolute deviation and lag-1 autocorrelation. The most unforgeable single kinematic dimension.

Φ_Jspec — Jerk Spectrum (30 dims): Frequency-domain analysis. Energy in 4 frequency bands, spectral slope (log-log power vs frequency), and spectral entropy. Human jerk exhibits 1/f^α scaling (α ≈ 1.0–1.5). AI jerk exhibits α > 2.0 (over-smoothed) or α ≈ 0 (white noise). Neither is human.`,
  },
  {
    id: "results",
    heading: "4. Live Verification Results",
    body: `The following results were generated by the MyShape CLI demo tool (myshape-demo) running the Rust core engine:

  Test Case              Presence Score   Verdict
  ─────────────────────────────────────────────────
  Genuine Human          0.9817           PASS ✓
  AI Forgery (GPT-5)     0.5857           FAIL ✗
  Impostor               0.0000           FAIL ✗

  Human—AI Gap: 0.3960

The AI forgery failed across four independent rejection dimensions:
  • TREMOR_ABSENT — 8–12 Hz physiological tremor missing
  • JERK_SPECTRUM_ANOMALY — 1/f spectral scaling violated
  • HURST_ANOMALY — Long-range dependence absent
  • OVER_SMOOTHED — Muscle micro-perturbations missing`,
  },
  {
    id: "integration",
    heading: "5. Integration: Five Lines to Proof of Intent",
    body: `TypeScript SDK (Node.js / Deno / Browser via WASM):

  import { MyShapeSDK } from "myshape-sdk";
  const myshape = await MyShapeSDK.init();
  const enrollment = myshape.createEnrollment(signatures, userId, device);
  const challenge = myshape.generateChallenge();
  const result = myshape.verifyIntent(challenge, motion, context, enrollment);
  if (result.verified) { executeTransaction(); }

Native CLI:

  cargo run --release --bin myshape-verify -- \
    --enrollment alice.enroll.json \
    --challenge session.challenge.json \
    --motion captured.motion.json \
    --risk high

Smart Contract (Solidity):

  function transferWithPresence(address to, uint256 amount,
      bytes calldata receipt, bytes calldata sig) external {
    require(verifyNodeSignature(receipt, sig));
    PresenceReceipt memory r = decodeReceipt(receipt);
    require(r.presenceScore >= minScore(amount));
    _transfer(msg.sender, to, amount);
  }`,
  },
  {
    id: "deeper-truth",
    heading: "6. The Deeper Truth",
    body: `Every AI motion model is a function approximator. It learns a mapping from inputs to outputs. It does not have a spinal cord, muscle spindles, a cerebellum, motor neurons firing asynchronously, a stretch reflex arc operating at 25 ms latency, tendons with viscoelastic properties, or joints with anisotropic friction.

An AI can approximate the output of these systems to arbitrary precision given enough data and compute. But the approximation will always be a projection — a lower-dimensional shadow of a higher-dimensional physical process.

The MyShape engine detects the shadow by measuring what the shadow cannot cast: the irreducible entropy of a living body.

The AI Paradox: The better AI gets at generating realistic motion, the more aggressively it smooths, averages, and regularizes — and the more detectable it becomes to spectral analysis. Every improvement in visual fidelity comes at the cost of spectral fidelity. The AI faces an impossible tradeoff: look more real, or be more real. It cannot do both.`,
  },
];

export default function WhitepaperClient() {
  return (
    <div className="min-h-screen bg-[#02040a] text-[#f8feff] font-mono selection:bg-cyan-500/30">
      <ProtocolHeader />
      <BackgroundParticles />

      <div className="relative z-10 max-w-3xl mx-auto px-6 pt-28 pb-16">
        {/* ── Header ── */}
        <div className="space-y-4 mb-14">
          <div className="text-cyan-500/50 text-[10px] tracking-[0.5em] uppercase">
            TECHNICAL_WHITEPAPER // CHAPTER_1
          </div>
          <h1 className="text-2xl md:text-3xl font-light tracking-[0.1em] text-white leading-tight">
            Why DeepSeek and GPT-5<br />
            <span className="text-cyan-300/80">Cannot Forge</span> the Human Kinetic Signature
          </h1>
          <p className="text-white/40 text-[12px] leading-relaxed max-w-xl">
            MyShape Protocol · June 2026 · v0.1
          </p>
          {/* ── Live status badge ── */}
          <div className="flex items-center gap-3 pt-2">
            <span className="flex items-center gap-1.5 text-cyan-400/70 text-[9px] tracking-[0.2em] uppercase">
              <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 shadow-[0_0_6px_rgba(34,211,238,0.6)] animate-pulse" />
              Engine v0.1.0
            </span>
            <span className="text-white/10">|</span>
            <span className="text-white/30 text-[9px] tracking-[0.15em]">25/25 tests pass</span>
            <span className="text-white/10">|</span>
            <span className="text-white/30 text-[9px] tracking-[0.15em]">Human—AI Gap: 0.3960</span>
          </div>
        </div>

        {/* ── Sections ── */}
        <div className="space-y-16">
          {SECTIONS.map((section) => (
            <section key={section.id} id={section.id}>
              <h2 className="text-cyan-400/60 text-[11px] tracking-[0.3em] uppercase mb-5 font-bold">
                {section.heading}
              </h2>
              {section.body.split("\n\n").map((para, i) => (
                <p
                  key={i}
                  className="text-white/45 text-[12px] leading-[1.85] mb-4"
                >
                  {para.trim()}
                </p>
              ))}

              {/* Special rendering for code blocks */}
              {section.id === "results" && (
                <div className="border border-cyan-500/15 bg-cyan-500/[0.02] p-5 my-6">
                  <pre className="text-white/50 text-[10px] leading-relaxed font-mono whitespace-pre">
                    {`  Test Case              Presence Score   Verdict
  ─────────────────────────────────────────────────
  Genuine Human          \x1b[32m0.9817\x1b[0m           \x1b[32mPASS\x1b[0m ✓
  AI Forgery (GPT-5)     \x1b[31m0.5857\x1b[0m           \x1b[31mFAIL\x1b[0m ✗
  Impostor               \x1b[31m0.0000\x1b[0m           \x1b[31mFAIL\x1b[0m ✗

  Human—AI Gap: \x1b[1m0.3960\x1b[0m`}
                  </pre>
                </div>
              )}

              {section.id === "integration" && (
                <div className="space-y-3 my-6">
                  <div className="border border-cyan-400/15 bg-cyan-400/[0.02] p-5">
                    <div className="text-cyan-400/40 text-[8px] tracking-[0.3em] uppercase mb-3">
                      TypeScript SDK
                    </div>
                    <pre className="text-cyan-200/60 text-[10px] leading-relaxed font-mono whitespace-pre-wrap">
{`import { MyShapeSDK } from "myshape-sdk";

const myshape = await MyShapeSDK.init();
const enrollment = myshape.createEnrollment(sigs, userId, device);
const challenge = myshape.generateChallenge();
const result = myshape.verifyIntent(
  challenge, motion, context, enrollment
);
if (result.verified) { executeTransaction(); }`}
                    </pre>
                  </div>
                  <div className="border border-white/5 bg-black/30 p-5">
                    <div className="text-white/20 text-[8px] tracking-[0.3em] uppercase mb-3">
                      Native CLI
                    </div>
                    <pre className="text-cyan-300/60 text-[10px] leading-relaxed font-mono whitespace-pre-wrap">
{`cargo run --release --bin myshape-verify -- \\
  --enrollment alice.enroll.json \\
  --challenge session.challenge.json \\
  --motion captured.motion.json \\
  --risk high`}
                    </pre>
                  </div>
                </div>
              )}
            </section>
          ))}
        </div>

        {/* ── Footer CTA ── */}
        <div className="mt-20 pt-10 border-t border-white/5">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="space-y-1">
              <p className="text-white/20 text-[9px] tracking-[0.3em] uppercase">
                Ready to integrate?
              </p>
              <p className="text-white/35 text-[10px]">
                Five lines of code. Zero data stored. Real human presence.
              </p>
            </div>
            <a
              href="/developers"
              className="inline-flex items-center gap-2 px-5 py-2.5 border border-cyan-400/25 text-cyan-300/70
                         text-[10px] tracking-[0.2em] uppercase font-mono
                         hover:bg-cyan-400/[0.04] hover:border-cyan-400/50 transition-all"
            >
              View SDK Reference
              <span className="text-cyan-400/40">→</span>
            </a>
          </div>
        </div>
      </div>

      <ProtocolFooter />
    </div>
  );
}
